package modelo;
// Generated 13-abr-2018 13:45:01 by Hibernate Tools 4.3.1


import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;


/**
 * Coche generated by hbm2java
 */
public class Coche  implements java.io.Serializable {


     private String matricula;
     private String modelo;
     private Time horaEntrada;
     private Time horaSalida;
     private int tiempoPermitido;

    public Coche() {
    }

	
    public Coche(String matricula, String modelo, int tiempoPermitido) {
        this.matricula = matricula;
        this.modelo = modelo;
        this.tiempoPermitido = tiempoPermitido;
    }
    public Coche(String matricula, String modelo, Time horaEntrada, Time horaSalida, int tiempoPermitido) {
       this.matricula = matricula;
       this.modelo = modelo;
       this.horaEntrada = horaEntrada;
       this.horaSalida = horaSalida;
       this.tiempoPermitido = tiempoPermitido;
    }

   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Time getHoraEntrada() {
        return this.horaEntrada;
    }
    
    public void setHoraEntrada(Time horaEntrada) {
        this.horaEntrada = horaEntrada;
    }
    public Time getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Time horaSalida) {
        this.horaSalida = horaSalida;
    }
    public int getTiempoPermitido() {
        return this.tiempoPermitido;
    }
    
    public void setTiempoPermitido(int tiempoPermitido) {
        this.tiempoPermitido = tiempoPermitido;
    }

    public long tiempoEnMinutos(Coche coche){
      //  DateFormat formatter = new SimpleDateFormat("HH:mm:ss");
      long hora_entrada,hora_salida, minutosAparcado = 0;
       
       // Time hora_entrada = new Time(formatter.parse(c.getHoraEntrada()).getTime());
       hora_entrada=(coche.getHoraEntrada().getTime())/60000;//getTime() devuelve un long con los minutos totales de la hora pasada por argumento
       hora_salida=(coche.getHoraSalida().getTime())/60000;
       String horaSalida=String.valueOf(hora_salida);
       
       minutosAparcado=hora_salida-hora_entrada;
      
       return minutosAparcado;
        
    }


}


