package reserva;
// Generated 19-abr-2018 18:44:34 by Hibernate Tools 4.3.1



/**
 * Tipoanimal generated by hbm2java
 */
public class Tipoanimal  implements java.io.Serializable {


     private Integer id;
     private String animal;

    public Tipoanimal() {
    }

    public Tipoanimal(String animal) {
       this.animal = animal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAnimal() {
        return this.animal;
    }
    
    public void setAnimal(String animal) {
        this.animal = animal;
    }




}


