package Modelo;
// Generated 18-mar-2018 8:57:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;

/**
 * Coche generated by hbm2java
 */
public class Coche  implements java.io.Serializable {


     private Integer id;
     private String matricula;
     private String modelo;
     private Date horaEntrada;
     private Date horaSalida;
     private int tiempoPermitido;

    public Coche() {
    }

	
    public Coche(String matricula, String modelo, int tiempoPermitido) {
        this.matricula = matricula;
        this.modelo = modelo;
        this.tiempoPermitido = tiempoPermitido;
    }
    public Coche(String matricula, String modelo, Date horaEntrada, Date horaSalida, int tiempoPermitido) {
       this.matricula = matricula;
       this.modelo = modelo;
       this.horaEntrada = horaEntrada;
       this.horaSalida = horaSalida;
       this.tiempoPermitido = tiempoPermitido;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Date getHoraEntrada() {
        return this.horaEntrada;
    }
    
    public void setHoraEntrada(Date horaEntrada) {
        this.horaEntrada = horaEntrada;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public int getTiempoPermitido() {
        return this.tiempoPermitido;
    }
    
    public void setTiempoPermitido(int tiempoPermitido) {
        this.tiempoPermitido = tiempoPermitido;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Coche other = (Coche) obj;
        if (this.tiempoPermitido != other.tiempoPermitido) {
            return false;
        }
        if (!Objects.equals(this.matricula, other.matricula)) {
            return false;
        }
        if (!Objects.equals(this.modelo, other.modelo)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.horaEntrada, other.horaEntrada)) {
            return false;
        }
        if (!Objects.equals(this.horaSalida, other.horaSalida)) {
            return false;
        }
        return true;
    }


}


